# Generated by Django 4.0.5 on 2022-07-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='año',
            field=models.IntegerField(verbose_name='Año: '),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(max_length=30, verbose_name='Marca '),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=30, verbose_name='Modelo '),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio $: '),
        ),
    ]
