# Generated by Django 4.0.5 on 2022-07-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutosApp', '0002_alter_auto_año_alter_auto_marca_alter_auto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='auto_comprado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Auto Comprado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor_nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendedor '),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio USD$ '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido '),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre '),
        ),
    ]
